######################################################################
# Automatically generated by qmake (2.01a) ?? 27. ??? 09:44:20 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
